#include "StepperMotor.hpp"
#ifndef __DEFINES__
#define __DEFINES__

//默认设置
#define DEF_ENA_TYPE LOW_TO_ENABLE
#define DEF_CLOCKWISE_TYPE HIGH_TO_CLOCKWISE

//电机信息
#define MOTER0_PUL 38
#define MOTER0_DIR 39
#define MOTER0_ENA 40
#define MOTER0_ROUND_PUL 6400
#define MOTER0_DIVIDER 5
#define MOTER0_ENA_TYPE LOW_TO_ENABLE
#define MOTER0_CLOCKWISE_TYPE LOW_TO_CLOCKWISE

#define MOTER1_PUL 7
#define MOTER1_DIR 6
#define MOTER1_ENA 5
#define MOTER1_ROUND_PUL 800
#define MOTER1_DIVIDER 84
#define MOTER1_ENA_TYPE LOW_TO_ENABLE
#define MOTER1_CLOCKWISE_TYPE LOW_TO_CLOCKWISE

#define MOTER2_PUL 26
#define MOTER2_DIR 27
#define MOTER2_ENA 28
#define MOTER2_ROUND_PUL 1600
#define MOTER2_DIVIDER 25.75
#define MOTER2_ENA_TYPE LOW_TO_ENABLE
#define MOTER2_CLOCKWISE_TYPE HIGH_TO_CLOCKWISE

#define MOTER3_PUL 11
#define MOTER3_DIR 10
#define MOTER3_ENA 9
#define MOTER3_ROUND_PUL 6400
#define MOTER3_DIVIDER 6
#define MOTER3_ENA_TYPE LOW_TO_ENABLE
#define MOTER3_CLOCKWISE_TYPE LOW_TO_CLOCKWISE

#define MOTER4_PUL 30
#define MOTER4_DIR 31
#define MOTER4_ENA 32
#define MOTER4_ROUND_PUL 6400
#define MOTER4_DIVIDER 4
#define MOTER4_ENA_TYPE LOW_TO_ENABLE
#define MOTER4_CLOCKWISE_TYPE LOW_TO_CLOCKWISE

#define MOTER5_PUL 34
#define MOTER5_DIR 35
#define MOTER5_ENA 36
#define MOTER5_ROUND_PUL 6400
#define MOTER5_DIVIDER 1
#define MOTER5_ENA_TYPE LOW_TO_ENABLE
#define MOTER5_CLOCKWISE_TYPE HIGH_TO_CLOCKWISE

#endif